
import type { Metadata } from 'next';

import './../styles/globals.css';
import dynamic from 'next/dynamic';
import Preloader from '@/components/Preloader';
import { Roboto, Dela_Gothic_One } from 'next/font/google';
import { PreloaderProvider } from '@/contexts/PreloaderContext';

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

const DelaGothicOne = Dela_Gothic_One({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Navbar = dynamic(() => import('@/components/Navbar'), { ssr: false });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PreloaderProvider>
      <html lang='sk'>
        <body className={roboto.className}>
          <Preloader />
          <Navbar />
          {children}
        </body>
      </html>
    </PreloaderProvider>
  );
}
